[[func_param_config.func_param_list]]
function_id = "color_detect"
returns = { web = true, gpio = true }
args = [
    "debug_model=false",
    "loop_count=5",
    "radius_ratio=0.4",
    "detect_area_access_rate=0.8",
    "color.red=0,50,160,255,110,255",
    "color.blue=100,137,124,255,56,255",
    "color.green=50,100,91,255,85,255",
    "color.black=0,179,0,255,0,76",
    "color.white=0,170,0,55,120,255",
    "color_light_pin=17",
    "qr_light_pin=22",
    "gpio_light_pin=27",
]

[[func_param_config.func_param_list]]
function_id = "qr_detect"
returns = { web = true, gpio = true }
args = [
    "debug_model=false",
    "color_light_pin=17",
    "qr_light_pin=22",
    "gpio_light_pin=27",
]

[[func_param_config.func_param_list]]
function_id = "cross_detect"
returns = { web = true, gpio = false }
args = []

[[func_param_config.func_param_list]]
function_id = "debug_fun"
returns = { web = true, gpio = false }
args = ["loop_source"]
